<a href="https://colab.research.google.com/github/MADHIREDDIKARTHIK/abc/blob/main/ml%20exp1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np

In [6]:
data= pd.read_csv("/content/netflix_revenue_updated.csv")
data

,Date,Global Revenue,UCAN Streaming Revenue,EMEA Streaming Revenue,LATM Streaming Revenue,APAC Streaming Revenue,UCAN Members,EMEA Members,LATM Members,APAC Members,UCAN ARPU,EMEA ARPU,LATM ARPU,APAC ARPU,Netflix Streaming Memberships
0,31-03-2019,4520992000,2256851000,1233379000,630472000,319602000,66633000,42542000,27547000,12141000,11.45,10.23,7.84,9.37,148863000
1,30-06-2019,4923116000,2501199000,1319087000,677136000,349494000,66501000,44229000,27890000,12942000,12.52,10.13,8.14,9.29,151562000
2,30-09-2019,5244905000,2621250000,1428040000,741434000,382304000,67114000,47355000,29380000,14485000,13.08,10.40,8.63,9.29,158334000
3,31-12-2019,5467434000,2671908000,1562561000,746392000,418121000,67662000,51778000,31417000,16233000,13.22,10.51,8.18,9.07,167090000
4,31-03-2020,5767691000,2702776000,1723474000,793453000,483660000,69969000,58734000,34318000,19835000,13.09,10.40,8.05,8.94,182856000
5,30-06-2020,6148286000,2839670000,1892537000,785368000,569140000,72904000,61483000,36068000,22492000,13.25,10.50,7.44,8.96,192947000
6,30-09-2020,6435637000,2933445000,2019083000,789384000,634891000,73081000,62242000,36324000,23504000,13.40,10.88,7.27,9.20,195151000
7,31-12-2020,6644442000,2979505000,2137158000,788522000,684609000,73936000,66698000,37537000,25492000,13.51,11.05,7.12,9.32,203663000
8,31-03-2021,7163282000,3170972000,2343674000,836647000,762414000,74384000,68508000,37894000,26853000,14.25,11.56,7.39,9.71,207639000
9,30-06-2021,7341777000,3234643000,2400480000,860882000,799480000,73951000,68696000,38658000,27875000,14.54,11.66,7.50,9.74,209180000
10,30-09-2021,7483467000,3257697000,2432239000,915297000,834002000,74024000,70500000,38988000,30051000,14.68,11.65,7.86,9.60,213563000
11,31-12-2021,7709318000,3308788000,2523426000,964150000,870705000,75215000,74036000,39961000,32632000,14.78,11.64,8.14,9.26,221844000
12,31-03-2022,7867767000,3350424000,2561831000,998948000,916754000,74579000,73733000,39610000,33719000,14.91,11.56,8.37,9.21,221641000
13,30-06-2022,7970141000,3537863000,2457235000,1030234000,907719000,73283000,72966000,39624000,34799000,15.95,11.17,8.67,8.83,220672000
14,30-09-2022,7925589000,3601565000,2375814000,1023945000,889037000,73387000,73534000,39936000,36228000,16.37,10.81,8.58,8.34,223085000
15,31-12-2022,7852053000,3594791000,2350135000,1016846000,856711000,74296000,76729000,41699000,38023000,16.23,10.43,8.30,7.69,230747000
16,31-03-2023,8161503000,3608645000,2517641000,1070192000,933523000,74398000,77373000,41249000,39478000,16.18,10.89,8.60,8.03,232498000
17,30-06-2023,8187301000,3599448000,2562170000,1077435000,919273000,75571000,79807000,42466000,40546000,16.00,10.87,8.58,7.66,238390000
18,30-09-2023,8541668000,3735133000,2693146000,1142811000,948216000,77321000,83760000,43645000,42427000,16.29,10.98,8.85,7.62,247153000
19,31-12-2023,8832825000,3594791000,2783530000,1156023000,962715000,80128000,88813000,45997000,45338000,16.64,10.75,8.60,7.31,260276000
20,31-03-2024,9370440000,4224315000,2958153000,1165008000,1022924000,82658000,91729000,47720000,47495000,17.30,10.92,8.29,7.35,269602000

In [7]:
concepts=np.array(data)[:,:-1]
concepts

array([['31-03-2019', 4520992000, 2256851000, 1233379000, 630472000,
        319602000, 66633000, 42542000, 27547000, 12141000, 11.45, 10.23,
        7.84, 9.37],
       ['30-06-2019', 4923116000, 2501199000, 1319087000, 677136000,
        349494000, 66501000, 44229000, 27890000, 12942000, 12.52, 10.13,
        8.14, 9.29],
       ['30-09-2019', 5244905000, 2621250000, 1428040000, 741434000,
        382304000, 67114000, 47355000, 29380000, 14485000, 13.08, 10.4,
        8.63, 9.29],
       ['31-12-2019', 5467434000, 2671908000, 1562561000, 746392000,
        418121000, 67662000, 51778000, 31417000, 16233000, 13.22, 10.51,
        8.18, 9.07],
       ['31-03-2020', 5767691000, 2702776000, 1723474000, 793453000,
        483660000, 69969000, 58734000, 34318000, 19835000, 13.09, 10.4,
        8.05, 8.94],
       ['30-06-2020', 6148286000, 2839670000, 1892537000, 785368000,
        569140000, 72904000, 61483000, 36068000, 22492000, 13.25, 10.5,
        7.44, 8.96],
       ['30-09-2020', 6435637000, 2933445000, 2019083000, 789384000,
        634891000, 73081000, 62242000, 36324000, 23504000, 13.4, 10.88,
        7.27, 9.2],
       ['31-12-2020', 6644442000, 2979505000, 2137158000, 788522000,
        684609000, 73936000, 66698000, 37537000, 25492000, 13.51, 11.05,
        7.12, 9.32],
       ['31-03-2021', 7163282000, 3170972000, 2343674000, 836647000,
        762414000, 74384000, 68508000, 37894000, 26853000, 14.25, 11.56,
        7.39, 9.71],
       ['30-06-2021', 7341777000, 3234643000, 2400480000, 860882000,
        799480000, 73951000, 68696000, 38658000, 27875000, 14.54, 11.66,
        7.5, 9.74],
       ['30-09-2021', 7483467000, 3257697000, 2432239000, 915297000,
        834002000, 74024000, 70500000, 38988000, 30051000, 14.68, 11.65,
        7.86, 9.6],
       ['31-12-2021', 7709318000, 3308788000, 2523426000, 964150000,
        870705000, 75215000, 74036000, 39961000, 32632000, 14.78, 11.64,
        8.14, 9.26],
       ['31-03-2022', 7867767000, 3350424000, 2561831000, 998948000,
        916754000, 74579000, 73733000, 39610000, 33719000, 14.91, 11.56,
        8.37, 9.21],
       ['30-06-2022', 7970141000, 3537863000, 2457235000, 1030234000,
        907719000, 73283000, 72966000, 39624000, 34799000, 15.95, 11.17,
        8.67, 8.83],
       ['30-09-2022', 7925589000, 3601565000, 2375814000, 1023945000,
        889037000, 73387000, 73534000, 39936000, 36228000, 16.37, 10.81,
        8.58, 8.34],
       ['31-12-2022', 7852053000, 3594791000, 2350135000, 1016846000,
        856711000, 74296000, 76729000, 41699000, 38023000, 16.23, 10.43,
        8.3, 7.69],
       ['31-03-2023', 8161503000, 3608645000, 2517641000, 1070192000,
        933523000, 74398000, 77373000, 41249000, 39478000, 16.18, 10.89,
        8.6, 8.03],
       ['30-06-2023', 8187301000, 3599448000, 2562170000, 1077435000,
        919273000, 75571000, 79807000, 42466000, 40546000, 16.0, 10.87,
        8.58, 7.66],
       ['30-09-2023', 8541668000, 3735133000, 2693146000, 1142811000,
        948216000, 77321000, 83760000, 43645000, 42427000, 16.29, 10.98,
        8.85, 7.62],
       ['31-12-2023', 8832825000, 3594791000, 2783530000, 1156023000,
        962715000, 80128000, 88813000, 45997000, 45338000, 16.64, 10.75,
        8.6, 7.31],
       ['31-03-2024', 9370440000, 4224315000, 2958153000, 1165008000,
        1022924000, 82658000, 91729000, 47720000, 47495000, 17.3, 10.92,
        8.29, 7.35]], dtype=object)

In [8]:
target=np.array(data)[:,-1]
target

array([148863000, 151562000, 158334000, 167090000, 182856000, 192947000,
       195151000, 203663000, 207639000, 209180000, 213563000, 221844000,
       221641000, 220672000, 223085000, 230747000, 232498000, 238390000,
       247153000, 260276000, 269602000], dtype=object)

In [17]:
def train(con,tar):
  for i,val in enumerate(tar):
    if val=='yes':
      specific_h=con[i].copy()
      break
  for i,val in enumerate(con):
    if tar[i]=='yes':
      for x in range(len(specific_h)):
        if val[x]!=specific_h[x]:
          specific_h[x]='?'
        else:
          pass
      return specific_h
print("n The final hypothesis is:",train(data,target))

n The final hypothesis is: None

In [18]:
import pandas as pd
import numpy as np

In [19]:
data= pd.read_csv("/content/data.csv")
data

     sky air temp humidity    wind water forecast enjoy sport
0  sunny     warm   normal  strong  warm     same         yes
1  sunny     warm     high  strong  warm     same         yes
2  rainy     cold     high  strong  warm   change          no
3  sunny     warm     high  strong  cool   change         yes

In [34]:
concepts=np.array(data)[:,-1]
concepts

array(['yes', 'yes', 'no', 'yes'], dtype=object)

In [35]:
target=np.array(data)[:,-1]
target

array(['yes', 'yes', 'no', 'yes'], dtype=object)

In [50]:

def train(con,tar):
  for i,val in enumerate(tar):
    if val=='yes':
      specific_h=con[i].copy() # Access numpy array using integer indexing
      break
  for i,val in enumerate(con):
    if tar[i]=='yes':
      for x in range(len(specific_h)):
        if val[x]!=specific_h[x]:
          specific_h[x]='?'
        else:
          pass
      return specific_h

In [54]:
print("n The final hypothesis is:",train(concepts,target))

n The final hypothesis is: ['sunny' 'warm' 'normal' 'strong' 'warm' 'same']